#!/usr/bin/env bash

### BEGIN INIT INFO
# Provides:          tomcat
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start/stop/reload tomcat
# Description:       start/stop/reload tomcat
### END INIT INFO

CATALINA_PATH="/opt/apache-tomcat-8.0.26/bin/catalina.sh"
PORT=8080 # only used for querying server on startup/shutdown, not for changing port

start() {
    "${CATALINA_PATH}" start
    STATUS=1
    while [ "${STATUS}" -ne 0 ]; do
	    set +e
	    curl "http://localhost:${PORT}" &>/dev/null
	    STATUS="$?"
	    set -e
	    if [ "${STATUS}" -ne 0 ]; then
	        echo "waiting for server to start $(date)"
	        sleep 1
	    fi
	done
}

stop() {
    "${CATALINA_PATH}" stop
	STATUS=0
	while [ "${STATUS}" -eq 0 ]; do
	    set +e
	    curl "http://localhost:${PORT}" &>/dev/null
	    STATUS="$?"
	    set -e
	    if [ "${STATUS}" -eq 0 ]; then
	        echo "waiting for server to shutdown $(date)"
	        sleep 1
	    fi
	done
}

if [ $(whoami) != "root" ]; then
    echo "Must run as root."
    exit 1
fi

case "$1" in
    start)
        start
        exit 0
    ;;
    stop)
        stop
        exit 0
    ;;
    reload|restart|force-reload)
        stop
        start
        exit 0
    ;;
    **)
        echo "Usage: $0 {start|stop|reload}" 1>&2
        exit 1
    ;;
esac
